### ISSUE TITLE
CIFAR-10 dataset (png format) download link is Invalid

### ISSUE THREAD

**Issue by zhangjinsong3** [xuyan1115/Similarity-Adaptive-Deep-Hashing#1]
Thanks for your work, the download link of CIFAR10 dataset（png format）is invalid. Can you provide a new one ? Thanks.

**Comment by PhoenixLSQ** [comment]
Can you provide a new CIFAR10 dataset link,thanks!

**Comment by liujinxin1** [comment]
您好，我是一名在校学生，最近读了这篇论文想要复现结果时有些困难，看您也阅读复现这篇论文想向您请教一下代码中的具体问题，在ADMM文件夹里的ADMM.m文件里第120行，更新B时用了[Bk_tep, ~, ~, ~] = minFunc(@gradientB, B(:), options, constant, Z, lambda, rho1, rho2, rho3, rho4);语句，这个函数的第一个输入@gradientB我理解的是论文中公式（6）的导数，可是在此.m文件中我并没有看到计算公式（6)的代码，希望您在百忙之中能抽空回复，谢谢。
